### ISSUE TITLE
Cart View

### ISSUE THREAD

**Issue by IsaacScheff** [Wu-Tang-Lan-2108/DiagonShopper#5]
Front End:
React Component to display contents

Insert placeholder data for cart contents
-clearly designate the temporary code

Back End:
Cart model
-including quantity

**Comment by IsaacScheff** [comment]
Front End:
React Component to display contents

Insert placeholder data for cart contents
-clearly designate the temporary code 

Back End:
Cart model
-including quantity

**Comment by fjohngomez** [comment]
Wrote DB Model Cart ; Imported on Index
Wrote Post request in Express Route : Cart; 
Next Steps: 
Backend: 
- [x] PUT Route
- [x] DELETE Route

Frontend: 
- [ ] View Cart (component)
- [ ] Add/Delete Button
- [ ] Changing Qty
- [ ] Purchase Button

**Comment by GTea30** [comment]
remote branch: `origin/Cart`

**Comment by GTea30** [comment]
# Progress
## Work done
- Worked on wrapping up backend:
  - PUT Route
  - DELETE Route
  - GET route for user's specific cart
- Started work on the Frontend:
  - Skeletonized the cart list including sum of cart
  - Cart list currently living at /:userId/cart
## Todo
- [ ] Frontend
  - [ ] Finish single cart component
    - [x] Price
    - [ ] Quantity
    - [x] Remove from Cart Button
  - [ ] Cookie integration for Guest
  - [x] Button functionality

**Comment by GTea30** [comment]
# Progress
2021-09-23

## Work Done
- Refactored Cart model into a Cart Item and Order Models (including associations)

## Todo
- [ ] Finish Single Cart Component
  - [ ] Changing Quantity
  - [x] Remove from Cart Button functionality
- [ ] Purchase Functionality

**Comment by fjohngomez** [comment]
### Progress:
9/24/21

### Work Done:
- Delete CartItem from Store/DB 
- Update QTY in cart - Pending error fix on backend qty update.

## To Do
- [ ] Purchase button / Functionality
- [ ] Add Item to Cart
- [ ] Add Type to Order table

**Comment by AI21212019** [comment]
### **Progress:**

9/27/21

### **Work Done:**

Purchase button added
Routers for Order table added
Redux setup and components for orders created
### **To Do**

- [ ] Purchase button optimization
- [ ] merge branch to main
