### ISSUE TITLE
Log In Admin

### ISSUE THREAD

**Issue by IsaacScheff** [Wu-Tang-Lan-2108/DiagonShopper#6]
Front End:
- [ ] Components: Only accessible to Admin
- [ ] AllProductView (Add/ Edit/ Delete Product)
- [ ] AllUsersView

Back End:
- [ ] User model => Add User type: Admin/User(default)
- [ ] Model Associations
- [ ] Post/Put/Delete Route added for /api/products
- [ ] Seed Master Admin

Design: 
- [ ] Add WireFrames for AllUsersView
- [ ] Add WireFrames for AllProductsAdminView

**Comment by fjohngomez** [comment]
- [ ] Add WireFrames for AllUsersView
- [ ] Add WireFrames for AllProductsAdminView

**Comment by AI21212019** [comment]
# **Progress**

## Work done

backend:
POST Route
PUT Route
DELETE Route

Frontend:
All product view component with a delete button 

## **Todo**

 Frontend

- [x] create and update form components
- [ ] connect to database as an admin
- [x] local state for guest 


Design:

- [ ] wireframes for Admin/user/guest
